version: '3'
services:
  #PHP Service
  app:
    build:
      context: .
      args:
        - PHP_VERSION=${PHP_VERSION}
    image: wd/php-app
    restart: unless-stopped
    environment:
      TZ: ${TZ}
      ENV: ${ENV}
    volumes:
      - ../code/:/var/www/html
    networks:
      - wd-network

  #Nginx Service
  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "${PROXY_PORT}:80"
    environment:
      TZ: ${TZ}
    volumes:
      - ../code/public:/var/www/html
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - wd-network

#Docker Networks
networks:
  wd-network: